blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('create_blog/', BlogCreateView.as_view(), name='create_blog'),
    path('blog/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='blog_detail'),
    path('edit_blog/<int:pk>/', BlogUpdateView.as_view(), name='edit_blog'),
    path('delete_blog/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.services import toggle_sending
from mailing.views import MailingListView, MailingCreateView, ClientListView, ClientCreateView, \
    ClientUpdateView, ClientDeleteView, MessageListView, MessageCreateView, MessageUpdateView, MessageDeleteView, \
    MailingDetailView, MailingUpdateView, MailingDeleteView, send_mailing_to_clients, mailing_logs, main_page_view

from mailing.apps import MailingConfig

app_name = MailingConfig.name

urlpatterns = [
    path('', main_page_view, name='home'),
    path('mailing/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/create_mailing/', MailingCreateView.as_view(), name='create_mailing'),
    path('mailing/mailing_detail/<int:pk>/', cache_page(60)(MailingDetailView.as_view()), name='mailing_detail'),
    path('mailing/edit_mailing/<int:pk>/', MailingUpdateView.as_view(), name='edit_mailing'),
    path('mailing/delete_mailing/<int:pk>/', MailingDeleteView.as_view(), name='delete_mailing'),
    path('mailing/clients/', ClientListView.as_view(), name='client_list'),
    path('mailing/clients/create_client/', ClientCreateView.as_view(), name='create_client'),
    path('mailing/clients/edit_client/<int:pk>/', ClientUpdateView.as_view(), name='edit_client'),
    path('mailing/clients/delete_client/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),
    path('mailing/messages/', MessageListView.as_view(), name='message_list'),
    path('mailing/messages/create_message/', MessageCreateView.as_view(), name='create_message'),
    path('mailing/messages/edit_message/<int:pk>/', MessageUpdateView.as_view(), name='edit_message'),
    path('mailing/messages/delete_message/<int:pk>/', MessageDeleteView.as_view(), name='delete_message'),
    path('mailing/send_mailing/', send_mailing_to_clients, name='send_mailing'),
    path('mailing/logs/<int:pk>/', mailing_logs, name='log_list'),
    path('mailing/sending/<int:pk>/', toggle_sending, name='toggle_sending'),
]

mailing/forms.py
from django import forms

from mailing.models import Mailing, Client, Message


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != "is_current_version":
                field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):
    """
     Создает форму для создания рассылки
    """
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # определяем список клиентов для рассылки, принадлежащих пользователю
        self.fields['mailing_clients'].queryset = Client.objects.filter(client_owner=user)

        # определяем список сообщений для рассылки, принадлежащих пользователю
        self.fields['mailing_message'].queryset = Message.objects.filter(message_owner=user)

    class Meta:
        """
        Определяет параметры формы
        """
        model = Mailing

        exclude = ('mailing_log', 'mailing_owner')  # выводит в форму все поля, кроме указанных
        widgets = {
            'mailing_time_start': forms.DateTimeInput(
                attrs={'type': 'datetime-local'}
            ),
            'mailing_time_finish': forms.DateTimeInput(
                attrs={'type': 'datetime-local'})
        }


class ClientForm(StyleFormMixin, forms.ModelForm):
    """
     Создает форму для создания клиента
    """

    class Meta:
        """
        Определяет параметры формы
        """
        model = Client

        exclude = ('client_owner',)  # выводит в форму все поля, кроме указанных


class MessageForm(StyleFormMixin, forms.ModelForm):
    """
     Создает форму для создания сообщения
    """

    class Meta:
        """
        Определяет параметры формы
        """
        model = Message

        exclude = ('message_owner',)  # выводит в форму все поля, кроме указанных

mailing/views.py
import datetime
from random import sample

import pytz
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse

from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from blog.models import Blog
from mailing.forms import MailingForm, ClientForm, MessageForm
from mailing.models import Mailing, Client, Message, Log
from mailing.services import sending_email


class MailingListView(ListView):
    """
    Выводит информаццию о рассылках пользователя
    """
    model = Mailing
    template_name = 'mailing/mailing_list.html'

    def get_queryset(self, *args, **kwargs):
        """
        Выводит в список только рассылки для конкретного пользователя
        """
        queryset = super().get_queryset(*args, **kwargs)

        try:
            user = self.request.user

            # если суперпользователь или менеджер, выводит все рассылки
            if user.is_superuser or user.groups.filter(name='manager'):
                return queryset

            # если пользователь, выводит все рассылки
            else:
                queryset = queryset.filter(mailing_owner=user)
                return queryset

        except TypeError:
            pass

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(MailingListView, self).get_context_data(**kwargs)

        context['title'] = 'Рассылки'
        context['title_2'] = 'мои рассылки'
        context['title_3'] = ('(Перед созданием рассылки необходимо занести клиента и создать сообщение. '
                              'Кнопка отправить рассылки сейчас позволяет запустить рассылки вне расписания)')

        return context


class MailingCreateView(LoginRequiredMixin, CreateView):
    """
    Выводит форму создания рассылки
    """
    model = Mailing
    form_class = MailingForm

    success_url = reverse_lazy('mailing:mailing_list')

    def form_valid(self, form):
        """
        Проверяем данные на правильность заполнения
        """

        user = self.request.user
        self.object = form.save()
        self.object.mailing_owner = user
        self.object.save()

        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class MailingDetailView(DetailView):
    """
    Выводит информаццию об одной рассылке
    """
    model = Mailing

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(MailingDetailView, self).get_context_data(**kwargs)

        context['title'] = 'Рассылки'
        context['title_2'] = 'информация о рассылке'

        return context


class MailingUpdateView(UpdateView):
    """
    Выводит форму редактирования рассылки
    """
    model = Mailing
    form_class = MailingForm

    success_url = reverse_lazy('mailing:mailing_list')

    def form_valid(self, form):
        """
        Проверяем данные на правильность заполнения
        """
        self.object = form.save()
        self.object.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(MailingUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Рассылки'
        context['title_2'] = 'Редактирование рассылки'
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class MailingDeleteView(DeleteView):
    """
    Выводит форму удаления рассылки
    """
    model = Mailing

    success_url = reverse_lazy('mailing:mailing_list')

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(MailingDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'Рассылки'
        context['title_2'] = 'Удаление рассылки'
        return context


class ClientListView(ListView):
    """
    Выводит информаццию о клиентах пользователя
    """
    model = Client
    template_name = 'mailing/client_list.html'

    def get_queryset(self, *args, **kwargs):
        """
        Выводит в список только клиентов конкретного пользователя
        """
        queryset = super().get_queryset(*args, **kwargs)

        queryset = queryset.filter(client_owner=self.request.user)

        return queryset

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(ClientListView, self).get_context_data(**kwargs)

        context['title'] = 'Клиенты'
        context['title_2'] = 'мои клиенты для рассылок'

        return context


class ClientCreateView(LoginRequiredMixin, CreateView):
    """
    Выводит форму создания клиента
    """
    model = Client
    form_class = ClientForm

    success_url = reverse_lazy('mailing:client_list')

    def form_valid(self, form):
        """
        Проверяем данные на правильность заполнения
        """
        self.object = form.save()
        self.object.client_owner = self.request.user
        self.object.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(ClientCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Клиенты'
        context['title_2'] = 'Создание клиента'
        return context


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """
    Выводит форму редактирования клиента
    """
    model = Client
    form_class = ClientForm

    success_url = reverse_lazy('mailing:client_list')

    def form_valid(self, form):
        """
        Проверяем данные на правильность заполнения
        """
        self.object = form.save()
        self.object.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(ClientUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Клиенты'
        context['title_2'] = 'Редактирование клиента'
        return context


class ClientDeleteView(DeleteView):
    """
    Выводит форму удаления клиента
    """
    model = Client

    success_url = reverse_lazy('mailing:client_list')

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(ClientDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'Клиенты'
        context['title_2'] = 'Удаление клиента'
        return context


class MessageListView(LoginRequiredMixin, ListView):
    """
    Выводит информаццию о сообщениях пользователя для рассылок
    """
    model = Message
    template_name = 'mailing/message_list.html'

    def get_queryset(self, *args, **kwargs):
        """
        Выводит в список только сообщения конкретного пользователя
        """
        queryset = super().get_queryset(*args, **kwargs)

        queryset = queryset.filter(message_owner=self.request.user)

        return queryset

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(MessageListView, self).get_context_data(**kwargs)

        context['title'] = 'Сообщения'
        context['title_2'] = 'мои сообщения для рассылок'

        return context


class MessageCreateView(LoginRequiredMixin, CreateView):
    """
    Выводит форму создания клиента
    """
    model = Message
    form_class = MessageForm

    success_url = reverse_lazy('mailing:message_list')

    def form_valid(self, form):
        """
        Проверяем данные на правильность заполнения
        """
        self.object = form.save()
        self.object.message_owner = self.request.user
        self.object.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(MessageCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Сообщения'
        context['title_2'] = 'Создание сообщения'
        return context


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """
    Выводит форму редактирования сообщения
    """
    model = Message
    form_class = MessageForm

    success_url = reverse_lazy('mailing:message_list')

    def form_valid(self, form):
        """
        Проверяем данные на правильность заполнения
        """
        self.object = form.save()
        self.object.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(MessageUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Сообщения'
        context['title_2'] = 'Редактирование сообщения'
        return context


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    """
    Выводит форму удаления сообщения
    """
    model = Message

    success_url = reverse_lazy('mailing:message_list')

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(MessageDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'Сообщения'
        context['title_2'] = 'Удаление сообщения'
        return context


def send_mailing_to_clients(request):
    """
    Функция отправки рассылок клиентам
    """

mailing/templates/mailing/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Рассылки - {{ title }}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% include 'mailing/includes/inc_mailing_up_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-6">{{ title }}</h1>
    <p class="lead">{{ title_2 }}</p>
    <p class="text-muted">{{ title_3 }}</p>
</div>

<div class="col-12">
    <div class="row">
        {% block content_1 %}
        {% endblock %}
    </div>
</div>
<br>


{% block content %}

<div class="row py-lg-2">
    <div class="col-lg-4 col-md-6 mx-auto">
        <div class="row text-center">
            <div class="card shadow-sm">
                <div class="card-body">
                    <p class="card-text">Последние новости сервиса</p>

                    <small class="text-body-secondary">
                        Количество рассылок всего - {{ mailings_count }}</small>
                    <br>
                    <small class="text-body-secondary">
                        Количество активных рассылок - {{ mailings_is_sending }}</small>
                    <br>
                    <small class="text-body-secondary">
                        Количество уникальных клиентов для рассылок - {{ clients_count }}</small>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-2">

                {% for blog in blog_list %}

                <div class="col-4">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <p class="card-text">Статья: {{ blog.blog_title }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="card-header">
                                    <img class="img-thumbnail"
                                         src="/media/{{ blog.blog_preview }}" width="150"
                                         alt="Card image cap"/>
                                </div>
                                <div class="btn-group">
                                    <a type="button" class="btn btn-bg btn-outline-secondary"
                                       href="{% url 'blog:blog_detail' pk=blog.id %}">Читать</a>
                                </div>
                            </div>
                            <br>
                            <small class="text-body-secondary">
                                Количество просмотров - {{ blog.blog_views_count }}</small>
                            <br>
                            <small class="text-body-secondary">
                                Автор - {{ blog.blog_owner|default:"Не определен" }}</small>
                        </div>
                    </div>
                </div>

                {% endfor %}

            </div>
        </div>
    </div>

    {% endblock %}

    {% include 'mailing/includes/inc_mailing_bottom_menu.html' %}

</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}


{% block content %}

    <div class="col-lg-3 col-md-8 mx-auto">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить клиента {{ object.client_email }} ?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a class="btn btn-warning" href="{% url 'mailing:client_list' %}">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

mailing/templates/mailing/client_form.html
{% extends 'mailing/base.html' %}


{% block content %}

<div class="col-lg-3 col-md-8 mx-auto">
    <form method="post" enctype="multipart/form-data">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">
                    {% if object %}
                    Редактирование клиента
                    {% else %}
                    Создание клиента
                    {% endif %}
                </h4>
            </div>
            <div class="card-body">

                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    {% if object %}
                    Изменить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
            </div>
        </div>

    </form>
</div>

{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}

{% block content_1 %}
<div class="row py-lg-2">
    <div class="col-lg-11 col-md-8 mx-auto">
        {% if user.is_authenticated %}
        <a class="btn btn-outline-primary" href="{% url 'mailing:create_client' %}">Создать клиента</a>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block content %}

<div class="col-lg-8 col-md-6 mx-auto">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">email</th>
                <th scope="col">Имя</th>
                <th scope="col">Фамилия</th>
                <th scope="col">Редактирование</th>
            </tr>
            </thead>
            <tbody>
            {% for client in object_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ client.client_email }}</td>
                <td>{{ client.client_first_name }}</td>
                <td>{{ client.client_last_name }}</td>

                <td>
                    <a type="button" class="btn btn-sm btn-outline-secondary"
                       href="{% url 'mailing:edit_client' pk=client.id %}">Edit</a>
                    <a type="button" class="btn btn-sm btn-outline-danger"
                       href="{% url 'mailing:delete_client' pk=client.id %}">Delete</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
</div>

{% endblock %}

mailing/templates/mailing/log_list.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-lg-8 col-md-6 mx-auto">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Дата/время</th>
                <th scope="col">Клиент</th>
                <th scope="col">Статус</th>
                <th scope="col">Ответ сервера</th>
            </tr>
            </thead>
            <tbody>
            {% for log in logs %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ log.log_date_time }}</td>
                <td>{{ log.log_client }}</td>
                <td>{{ log.log_status }}</td>
                <td>{{ log.log_server_answer }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
</div>

{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}


{% block content %}

    <div class="col-lg-3 col-md-8 mx-auto">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить рассылку {{ object.mailing_title }} ?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a class="btn btn-warning" href="{% url 'mailing:mailing_list' %}">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-lg-6 col-md-8 mx-auto">
    <div class="card shadow-sm">
        <div class="card-body bg-secondary mb-3">
            <p class="text-white">Рассылка - {{ mailing.mailing_title }}</p>
            <div class="card shadow-sm">
                <p class="card-text-dark">{{ mailing.mailing_message.message_text }}</p>
            </div>
            <br>
            <div class="d-flex justify-content-between align-items-center">
                <div class="card shadow-sm">
                    <div class="btn-group">
                        {% if request.user == mailing.mailing_owner %}
                        <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'mailing:edit_mailing' pk=object.id %}">Edit</a>
                        <a type="button" class="btn btn-sm btn-outline-danger"
                           href="{% url 'mailing:delete_mailing' pk=object.id %}">Delete</a>
                        {% endif %}
                    </div>
                </div>

            </div>

        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}


{% block content %}

<div class="col-lg-3 col-md-8 mx-auto">
    <form method="post" enctype="multipart/form-data">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">
                    {% if object %}
                    Редактирование рассылки
                    {% else %}
                    Создание рассылки
                    {% endif %}
                </h4>
            </div>
            <div class="card-body">

                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    {% if object %}
                    Изменить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
            </div>
        </div>

    </form>
</div>

{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}

{% block content_1 %}
<div class="row py-lg-2">
    <div class="col-lg-11 col-md-8 mx-auto">
        {% if user.is_authenticated %}
        <a class="btn btn-outline-primary" href="{% url 'mailing:create_mailing' %}">Создать рассылку</a>
        <a class="btn btn-outline-primary" href="{% url 'mailing:message_list' %}">Мои сообщения</a>
        <a class="btn btn-outline-primary" href="{% url 'mailing:client_list' %}">Мои клиенты</a>
        <a type="button" class="btn btn-outline-success"
           href="{% url 'mailing:send_mailing' %}">Отправить рассылки сейчас</a>
        {% else %}
        <a class="btn btn-outline-primary">Создавать рассылки могут только зарегистрированные пользователи</a>
        {% endif %}
    </div>
</div>
{% endblock %}


{% block content %}

{% for mailing in object_list %}

<div class="col-lg-6 col-md-8 mx-auto">
    <div class="row text-center">
        <div class="card mb-6 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h5 class="my-0 fw-normal">Рассылка - {{ mailing.mailing_title }}
                    ({{ mailing.mailing_message.message_text|truncatechars:50 }})</h5>
            </div>
            <div class="card-body">
                <div class="mb-3">
                    <button class="w-100 btn btn-primary" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapseExample{{ forloop.counter }}" aria-expanded="false"
                            aria-controls="collapseExample">
                        Развернуть/свернуть
                    </button>
                    <div class="collapse" id="collapseExample{{ forloop.counter }}">
                        <div class="card card-body">
                            Автор рассылки - {{ mailing.mailing_owner }}
                            <br>
                            Начало рассылки - {{ mailing.mailing_time_start }}
                            <br>
                            Окончание рассылки - {{ mailing.mailing_time_finish }}
                            <br>
                            Периодичность рассылки - {{ mailing.mailing_period }}
                            <br>
                            Статус рассылки - {{ mailing.mailing_status }}
                            <br>
                            Клиенты рассылки -<br>
                            {% for client in mailing.mailing_clients.all %}
                            {{ client }}<br>
                            {% endfor %}
                            <br>
                        </div>
                        <br>
                        <div class="col">
                            <a type="button" class="btn btn-lg btn-outline-success"
                               href="{% url 'mailing:mailing_detail' pk=mailing.id %}">View</a>
                            {% if request.user == mailing.mailing_owner %}
                                <a type="button" class="btn btn-lg btn-outline-warning"
                                   href="{% url 'mailing:edit_mailing' pk=mailing.id %}">Edit</a>
                                <a type="button" class="btn btn-lg btn-outline-danger"
                                   href="{% url 'mailing:delete_mailing' pk=mailing.id %}">Delete</a>
                            {% endif %}
                                <a type="button" class="btn btn-lg btn-outline-secondary"
                                   href="{% url 'mailing:log_list' pk=mailing.id %}">Logs</a>
                            {% if request.user.is_staff %}
                                {% if mailing.mailing_status == 'рассылается' %}
                                <a type="button" class="btn btn-lg btn-warning"
                                   href="{% url 'mailing:toggle_sending' pk=mailing.id %}">Остановить рассылку</a>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br>

{% endfor %}

{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html' %}

{% block content_1 %}
<div class="row py-lg-2">
    <div class="col-lg-11 col-md-8 mx-auto">
        {% if user.is_authenticated %}
        <a class="btn btn-outline-primary" href="{% url 'mailing:create_message' %}">Создать сообщение</a>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block content %}

<div class="col-lg-8 col-md-6 mx-auto">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Название</th>
                <th scope="col">Сообщение</th>
                <th scope="col">Редактирование</th>
            </tr>
            </thead>
            <tbody>
            {% for message in object_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ message.message_title }}</td>
                <td>{{ message.message_text|truncatechars:100 }}</td>
                <td>
                    <a type="button" class="btn btn-sm btn-outline-secondary"
                       href="{% url 'mailing:edit_message' pk=message.id %}">Edit</a>
                    <a type="button" class="btn btn-sm btn-outline-danger"
                       href="{% url 'mailing:delete_message' pk=message.id %}">Delete</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
</div>

{% endblock %}