blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('create_blog/', BlogCreateView.as_view(), name='create_blog'),
    path('blog/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='blog_detail'),
    path('edit_blog/<int:pk>/', BlogUpdateView.as_view(), name='edit_blog'),
    path('delete_blog/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    """
    Класс для ведения блога
    """
    blog_title = models.CharField(max_length=150, verbose_name='Заголовок')
    blog_text = models.TextField(verbose_name='Содержимое')
    blog_preview = models.ImageField(upload_to='blog/', verbose_name='Превью', **NULLABLE)
    blog_slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    blog_date_creation = models.DateField(auto_now=False, auto_now_add=True, verbose_name='Дата публикации')
    blog_is_active = models.BooleanField(default=True, verbose_name='Опубликовано')
    blog_views_count = models.IntegerField(default=0, verbose_name='Просмотры')

    blog_owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                                   verbose_name='владелец', **NULLABLE)

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.blog_title}'

    class Meta:
        verbose_name = 'Статья'  # Настройка для наименования одного объекта
        verbose_name_plural = 'Статьи'  # Настройка для наименования набора объектов
        ordering = ('blog_title',)  # сортировка по наименованию

blog/forms.py
from django import forms

from blog.models import Blog
from mailing.models import Mailing, Client, Message


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != "is_current_version":
                field.widget.attrs['class'] = 'form-control'


class BlogForm(StyleFormMixin, forms.ModelForm):
    """
     Создает форму для создания товара
    """
    class Meta:
        """
        Определяет параметры формы
        """
        model = Blog

        fields = ('blog_title', 'blog_text', 'blog_preview')

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from blog.forms import BlogForm
from blog.models import Blog


class BlogListView(ListView):
    """
    Выводит список статей пользователя
    """
    model = Blog
    template_name = 'blog/blog_list.html'

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(BlogListView, self).get_context_data(**kwargs)
        context['title'] = 'Блог'
        context['title_2'] = 'Полезные статьи'
        return context

    def get_queryset(self, *args, **kwargs):
        """
        Выводит в список только опубликованные статьи
        """
        queryset = super().get_queryset(*args, **kwargs)

        try:
            user = self.request.user

            # если суперпользователь или менеджер, выводит все статьи
            if user.is_superuser or user.groups.filter(name='manager'):
                return queryset

            # если пользователь, выводит только его статьи
            else:
                queryset = queryset.filter(blog_owner=user)
                return queryset

        except TypeError:
            pass


class BlogCreateView(CreateView):
    """
    Выводит форму создания статьи
    """
    model = Blog
    form_class = BlogForm

    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        """
        Реализует заполнение формы блога
        """
        self.object = form.save()
        self.object.blog_owner = self.request.user
        self.object.save()

        if form.is_valid():
            new_article = form.save()
            new_article.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(BlogCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Блог'
        context['title_2'] = 'Создание статьи'
        return context


class BlogDetailView(DetailView):
    """
    Выводит информаццию о статье
    """
    model = Blog

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        context['title'] = 'Блог'
        context['title_2'] = 'Просмотр статьи'
        return context

    def get_object(self, queryset=None):
        """
        Считает количество просмотров статьи
        """
        self.object = super(BlogDetailView, self).get_object(queryset)
        self.object.blog_views_count += 1
        self.object.save()

        return self.object


class BlogUpdateView(UpdateView):
    """
    Выводит форму редактирования статьи
    """
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        """
        Реализует создание Slug — человекопонятный URL
        """
        if form.is_valid():
            new_article = form.save()
            new_article.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(BlogUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Блог'
        context['title_2'] = 'Изменение статьи'
        return context


class BlogDeleteView(DeleteView):
    """
    Выводит форму удаления статьи
    """
    model = Blog

    success_url = reverse_lazy('blog:blog_list')

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(BlogDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'Блог'
        context['title_2'] = 'Удаление статьи'
        return context

blog/templates/blog/blog_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}

    <div class="col-lg-3 col-md-8 mx-auto">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить статью: {{ blog.blog_title }} ?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a class="btn btn-warning" href="{% url 'blog:blog_list' %}">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-lg-6 col-md-8 mx-auto">
    <div class="card shadow-sm">
        <div class="card-body bg-secondary mb-3">
            <p class="text-white">Статья - {{ blog.blog_title }}</p>
            <div class="card shadow-sm">
                <p class="card-text-dark">{{ blog.blog_text }}</p>
            </div>
            <div class="col-5">
                <div class="card-md-4">
                    <div class="card-header">
                        <img class="card-img-top"
                             src="/media/{{ blog.blog_preview }}"
                             alt="Card image cap"/>
                    </div>
                </div>
            </div>
            <br>
            <div class="d-flex justify-content-between align-items-center">
                <div class="card shadow-sm">
                    <div class="btn-group">
                        {% if request.user == blog.blog_owner or request.user.is_staff %}
                        <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'blog:edit_blog' pk=blog.id %}">Edit</a>
                        <a type="button" class="btn btn-sm btn-outline-danger"
                           href="{% url 'blog:delete_blog' pk=blog.id %}">Delete</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mailing/base.html' %}

{% block content %}

    <div class="col-lg-3 col-md-8 mx-auto">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                {% if object %}
                                Изменить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailing/base.html' %}

{% block content_1 %}
<div class="row py-lg-2">
    <div class="col-lg-11 col-md-8 mx-auto">
        {% if user.is_authenticated %}
        <a class="btn btn-outline-primary" href="{% url 'blog:create_blog' %}">Создать статью</a>
        {% else %}
        <a class="btn btn-outline-primary">Создавать статьи могут только зарегистрированные пользователи</a>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block content %}

{% for blog in object_list %}
<div class="col-lg-6 col-md-8 mx-auto">
    <div class="row text-center">
        <div class="col-12">
            <div class="card mb-6 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h5 class="my-0 fw-normal">Статья - {{ blog.blog_title }}
                        ({{ blog.blog_text|truncatechars:50 }})</h5>
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        <button class="w-100 btn btn-primary" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseExample{{ forloop.counter }}" aria-expanded="false"
                                aria-controls="collapseExample">
                            Развернуть/свернуть
                        </button>
                        <div class="collapse" id="collapseExample{{ forloop.counter }}">
                            <div class="card card-body">
                                Количество просмотров - {{ blog.blog_views_count }}
                            <br>
                                Автор статьи - {{ blog.blog_owner }}
                            <br>
                            </div>
                            <br>
                            <div class="col">
                                <a type="button" class="btn btn-lg btn-outline-success"
                                   href="{% url 'blog:blog_detail' pk=blog.id %}">View</a>
                                {% if request.user == blog.blog_owner or request.user.is_staff %}
                                <a type="button" class="btn btn-lg btn-outline-warning"
                                   href="{% url 'blog:edit_blog' pk=blog.id %}">Edit</a>
                                <a type="button" class="btn btn-lg btn-outline-danger"
                                   href="{% url 'blog:delete_blog' pk=blog.id %}">Delete</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
{% endfor %}

{% endblock %}