blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('create_blog/', BlogCreateView.as_view(), name='create_blog'),
    path('blog/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='blog_detail'),
    path('edit_blog/<int:pk>/', BlogUpdateView.as_view(), name='edit_blog'),
    path('delete_blog/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from users.apps import UsersConfig
from users.services import toggle_activity
from users.views import RegisterView, UserConfirmEmailView, UserConfirmationSentView, UserConfirmedView, \
    UserConfirmationFailView, ProfileView, UserListView, UserDetailView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email_confirmation_sent/', UserConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', UserConfirmedView.as_view(), name='email_confirmed'),
    path('email_confirmation_failed/', UserConfirmationFailView.as_view(), name='email_confirmation_failed'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('user_list', UserListView.as_view(), name='user_list'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    ]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    VERSION_CHOICES = ((True, 'Действующий'), (False, 'Заблокирован'))

    email = models.EmailField(unique=True, verbose_name='почта')
    phone = models.CharField(max_length=35, verbose_name='телефон', blank=True, null=True)
    avatar = models.ImageField(upload_to='users/media/', verbose_name='аватар', blank=True, null=True)
    is_active = models.BooleanField(choices=VERSION_CHOICES, default=True, verbose_name='Статус пользователя')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from users.models import User


class UserRegisterForm(UserCreationForm):
    """
    Форма регистрации пользователя
    """
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserProfileForm(UserChangeForm):
    """
    Форма профиля пользователя
    """
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        """
        Дополнительные настройки
        """
        super().__init__(*args, **kwargs)

        # Позволяет не выводить в профиле поле пароля
        self.fields['password'].widget = forms.HiddenInput()

        # передаем в шаблон контроль формы
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ManagerUpdateUserProfileForm(UserChangeForm):
    """
    Форма профиля пользователя для редактирования менеджером
    """

    class Meta:
        model = User
        fields = ('is_active',)

    def __init__(self, *args, **kwargs):
        """
        Дополнительные настройки
        """
        super().__init__(*args, **kwargs)

        # Позволяет не выводить в профиле поле пароля
        self.fields['password'].widget = forms.HiddenInput()

        # передаем в шаблон контроль формы
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

users/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordResetDoneView
from django.core.cache import cache
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import CreateView, TemplateView, UpdateView, ListView, DetailView

from config import settings
from users.forms import UserRegisterForm, UserProfileForm, ManagerUpdateUserProfileForm
from users.models import User


class RegisterView(CreateView):
    """
    Регистрация нового пользователя и его валидация через письмо на email пользователя
    """
    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy('mailing:home')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        user.save()

        # формируем токен и ссылку для подтверждения регистрации
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        activation_url = reverse_lazy('users:confirm_email', kwargs={'uidb64': uid, 'token': token})

        current_site = '127.0.0.1:8000'

        send_mail(
            subject='Регистрация на платформе',
            message=f"Завершите регистрацию, перейдя по ссылке: http://{current_site}{activation_url}",
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return redirect('users:email_confirmation_sent')


class UserConfirmEmailView(View):
    """
    Подтверждение пользователем регистрации
    """
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('users:email_confirmed')
        else:
            return redirect('users:email_confirmation_failed')


class UserConfirmationSentView(PasswordResetDoneView):
    """
    Выводит информацию об отправке на почту подтверждения регистрации
    """
    template_name = "users/registration_sent_done.html"


class UserConfirmedView(TemplateView):
    """
    Выводит информацию об успешной регистрации пользователя
    """
    template_name = 'users/registration_confirmed.html'


class UserConfirmationFailView(View):
    """
    Выводит информацию о невозможности зарегистрировать пользователя
    """
    template_name = 'users/email_confirmation_failed.html'


class ProfileView(UpdateView):
    """
    Контроллер профиля пользователя
    """
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        """
        Позволяет делать необязательным передачу pk объекта
        """
        return self.request.user

    # def get_form_class(self):
    #     # product = self.get_object()
    #     user = self.request.user
    #
    #     if user.is_staff:  # проверяем права доступа
    #         return ManagerUpdateUserProfileForm  # если менеджер, то выводится отдельная форма
    #
    #     else:
    #         return UserProfileForm

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(ProfileView, self).get_context_data(**kwargs)

        context['title'] = 'Профиль'
        context['title_2'] = 'редактирование профиля пользователя'

        return context


class UserListView(PermissionRequiredMixin, ListView):
    """
    Выводит информаццию о пользователях
    """

    model = User
    permission_required = 'users.view_user'
    template_name = 'users/user_list.html'

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(UserListView, self).get_context_data(**kwargs)

        context['title'] = 'Пользователи'
        context['title_2'] = 'пользователи сервиса рассылок'

        return context


class UserDetailView(DetailView):
    """
    Выводит информаццию об одной рассылке
    """
    model = User

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(UserDetailView, self).get_context_data(**kwargs)

        context['title'] = 'Пользователь'
        context['title_2'] = 'информация о пользователе сервиса'

        return context

users/templates/users/email_confirmation_failed.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Ошибка</h4>
    <p>Не удалось подтвердить вашу электронную почту. Попробуйте еще раз</p>
</div>

{% endblock %}

users/templates/users/login.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-lg-3 col-md-8 mx-auto">
    <form method="post" enctype="multipart/form-data">
        <div class="card">
            <div class="card-header bg-secondary text-white text-center">
                <h4 class="card-title">Вход</h4>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Войти</button>
            </div>
            <div class="card-footer bg-secondary"></div>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-lg-3 col-md-8 mx-auto">
    <form method="post" enctype="multipart/form-data">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Регистрация</h4>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/registration_confirmed.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Успешно</h4>
    <p>Ваша электронная почта подтверждена</p>
</div>

{% endblock %}

users/templates/users/registration_sent_done.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="alert alert-warning" role="alert">
    <h4 class="alert-heading">Вам на почту, указанную при регистрации, отправлено письмо</h4>
    <br>
    <p>Для успешной регистрации перейдите по ссылке, указанной в письме</p>
</div>

{% endblock %}

users/templates/users/user_detail.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-lg-6 col-md-8 mx-auto">
    <div class="card shadow-sm">
        <div class="card-body bg-secondary mb-3">
            <p class="text-white">Пользователь - {{ user.email }}</p>
            <p class="text-white">Телефон - {{ user.phone|default:"Нет данных" }}</p>
            <div class="card shadow-sm">
                <img class="img-thumbnail"
                                         src="/media/{{ user.avatar }}" width="200"
                                         alt="Card image cap"/>
            </div>
            <br>
            <div class="d-flex justify-content-between align-items-center">
                <div class="card shadow-sm">
                    <div class="btn-group">
                        {% if request.user == mailing.mailing_owner %}
                        <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="#">Edit</a>
                        <a type="button" class="btn btn-sm btn-outline-danger"
                           href="#">Delete</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-lg-3 col-md-8 mx-auto">
    <form method="post" enctype="multipart/form-data">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Профиль</h4>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        </div>

    </form>

</div>

{% endblock %}

users/templates/users/user_list.html
{% extends 'mailing/base.html' %}

{% block content %}

    {% for object in object_list %}
    <div class="col-lg-3 col-md-6 mx-auto">
        <div class="card shadow-sm">
            <div class="card-body">
                <p class="card-text">{{ object }}</p>
                {% if object.is_superuser == False %}
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a type="button" class="btn btn-sm btn-outline-secondary"
                                href="{% url 'users:user_detail' pk=object.id %}">View</a>

                        {% if perms.users.delete_user %}
                        <a type="button" class="btn btn-sm btn-outline-danger"
                                href="{#}">Delete</a>
                        {% endif %}
                    </div>
                    {% if perms.users.change_user %}
                        {% if object.is_active %}
                            <a class="btn btn-warning" href="{% url 'users:toggle_activity' pk=object.id %}">Деактивировать</a>
                        {% else %}
                            <a class="btn btn-success" href="{% url 'users:toggle_activity' pk=object.id %}">Активировать</a>
                        {% endif %}
                    {% endif %}
                </div>
                {% else %}
                <h4 class="card-title">Доступ закрыт</h4>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}

{% endblock %}