blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('create_blog/', BlogCreateView.as_view(), name='create_blog'),
    path('blog/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='blog_detail'),
    path('edit_blog/<int:pk>/', BlogUpdateView.as_view(), name='edit_blog'),
    path('delete_blog/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.services import toggle_sending
from mailing.views import MailingListView, MailingCreateView, ClientListView, ClientCreateView, \
    ClientUpdateView, ClientDeleteView, MessageListView, MessageCreateView, MessageUpdateView, MessageDeleteView, \
    MailingDetailView, MailingUpdateView, MailingDeleteView, send_mailing_to_clients, mailing_logs, main_page_view

from mailing.apps import MailingConfig

app_name = MailingConfig.name

urlpatterns = [
    path('', main_page_view, name='home'),
    path('mailing/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/create_mailing/', MailingCreateView.as_view(), name='create_mailing'),
    path('mailing/mailing_detail/<int:pk>/', cache_page(60)(MailingDetailView.as_view()), name='mailing_detail'),
    path('mailing/edit_mailing/<int:pk>/', MailingUpdateView.as_view(), name='edit_mailing'),
    path('mailing/delete_mailing/<int:pk>/', MailingDeleteView.as_view(), name='delete_mailing'),
    path('mailing/clients/', ClientListView.as_view(), name='client_list'),
    path('mailing/clients/create_client/', ClientCreateView.as_view(), name='create_client'),
    path('mailing/clients/edit_client/<int:pk>/', ClientUpdateView.as_view(), name='edit_client'),
    path('mailing/clients/delete_client/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),
    path('mailing/messages/', MessageListView.as_view(), name='message_list'),
    path('mailing/messages/create_message/', MessageCreateView.as_view(), name='create_message'),
    path('mailing/messages/edit_message/<int:pk>/', MessageUpdateView.as_view(), name='edit_message'),
    path('mailing/messages/delete_message/<int:pk>/', MessageDeleteView.as_view(), name='delete_message'),
    path('mailing/send_mailing/', send_mailing_to_clients, name='send_mailing'),
    path('mailing/logs/<int:pk>/', mailing_logs, name='log_list'),
    path('mailing/sending/<int:pk>/', toggle_sending, name='toggle_sending'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from users.apps import UsersConfig
from users.services import toggle_activity
from users.views import RegisterView, UserConfirmEmailView, UserConfirmationSentView, UserConfirmedView, \
    UserConfirmationFailView, ProfileView, UserListView, UserDetailView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email_confirmation_sent/', UserConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', UserConfirmedView.as_view(), name='email_confirmed'),
    path('email_confirmation_failed/', UserConfirmationFailView.as_view(), name='email_confirmation_failed'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('user_list', UserListView.as_view(), name='user_list'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    ]

mailing/forms.py
from django import forms

from mailing.models import Mailing, Client, Message


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != "is_current_version":
                field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):
    """
     Создает форму для создания рассылки
    """
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # определяем список клиентов для рассылки, принадлежащих пользователю
        self.fields['mailing_clients'].queryset = Client.objects.filter(client_owner=user)

        # определяем список сообщений для рассылки, принадлежащих пользователю
        self.fields['mailing_message'].queryset = Message.objects.filter(message_owner=user)

    class Meta:
        """
        Определяет параметры формы
        """
        model = Mailing

        exclude = ('mailing_log', 'mailing_owner')  # выводит в форму все поля, кроме указанных
        widgets = {
            'mailing_time_start': forms.DateTimeInput(
                attrs={'type': 'datetime-local'}
            ),
            'mailing_time_finish': forms.DateTimeInput(
                attrs={'type': 'datetime-local'})
        }


class ClientForm(StyleFormMixin, forms.ModelForm):
    """
     Создает форму для создания клиента
    """

    class Meta:
        """
        Определяет параметры формы
        """
        model = Client

        exclude = ('client_owner',)  # выводит в форму все поля, кроме указанных


class MessageForm(StyleFormMixin, forms.ModelForm):
    """
     Создает форму для создания сообщения
    """

    class Meta:
        """
        Определяет параметры формы
        """
        model = Message

        exclude = ('message_owner',)  # выводит в форму все поля, кроме указанных

mailing/views.py
import datetime
from random import sample

import pytz
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse

from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from blog.models import Blog
from mailing.forms import MailingForm, ClientForm, MessageForm
from mailing.models import Mailing, Client, Message, Log
from mailing.services import sending_email


class MailingListView(ListView):
    """
    Выводит информаццию о рассылках пользователя
    """
    model = Mailing
    template_name = 'mailing/mailing_list.html'

    def get_queryset(self, *args, **kwargs):
        """
        Выводит в список только рассылки для конкретного пользователя
        """
        queryset = super().get_queryset(*args, **kwargs)

        try:
            user = self.request.user

            # если суперпользователь или менеджер, выводит все рассылки
            if user.is_superuser or user.groups.filter(name='manager'):
                return queryset

            # если пользователь, выводит все рассылки
            else:
                queryset = queryset.filter(mailing_owner=user)
                return queryset

        except TypeError:
            pass

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(MailingListView, self).get_context_data(**kwargs)

        context['title'] = 'Рассылки'
        context['title_2'] = 'мои рассылки'
        context['title_3'] = ('(Перед созданием рассылки необходимо занести клиента и создать сообщение. '
                              'Кнопка отправить рассылки сейчас позволяет запустить рассылки вне расписания)')

        return context


class MailingCreateView(LoginRequiredMixin, CreateView):
    """
    Выводит форму создания рассылки
    """
    model = Mailing
    form_class = MailingForm

    success_url = reverse_lazy('mailing:mailing_list')

    def form_valid(self, form):
        """
        Проверяем данные на правильность заполнения
        """

        user = self.request.user
        self.object = form.save()
        self.object.mailing_owner = user
        self.object.save()

        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class MailingDetailView(DetailView):
    """
    Выводит информаццию об одной рассылке
    """
    model = Mailing

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(MailingDetailView, self).get_context_data(**kwargs)

        context['title'] = 'Рассылки'
        context['title_2'] = 'информация о рассылке'

        return context


class MailingUpdateView(UpdateView):
    """
    Выводит форму редактирования рассылки
    """
    model = Mailing
    form_class = MailingForm

    success_url = reverse_lazy('mailing:mailing_list')

    def form_valid(self, form):
        """
        Проверяем данные на правильность заполнения
        """
        self.object = form.save()
        self.object.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(MailingUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Рассылки'
        context['title_2'] = 'Редактирование рассылки'
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class MailingDeleteView(DeleteView):
    """
    Выводит форму удаления рассылки
    """
    model = Mailing

    success_url = reverse_lazy('mailing:mailing_list')

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(MailingDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'Рассылки'
        context['title_2'] = 'Удаление рассылки'
        return context


class ClientListView(ListView):
    """
    Выводит информаццию о клиентах пользователя
    """
    model = Client
    template_name = 'mailing/client_list.html'

    def get_queryset(self, *args, **kwargs):
        """
        Выводит в список только клиентов конкретного пользователя
        """
        queryset = super().get_queryset(*args, **kwargs)

        queryset = queryset.filter(client_owner=self.request.user)

        return queryset

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(ClientListView, self).get_context_data(**kwargs)

        context['title'] = 'Клиенты'
        context['title_2'] = 'мои клиенты для рассылок'

        return context


class ClientCreateView(LoginRequiredMixin, CreateView):
    """
    Выводит форму создания клиента
    """
    model = Client
    form_class = ClientForm

    success_url = reverse_lazy('mailing:client_list')

    def form_valid(self, form):
        """
        Проверяем данные на правильность заполнения
        """
        self.object = form.save()
        self.object.client_owner = self.request.user
        self.object.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(ClientCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Клиенты'
        context['title_2'] = 'Создание клиента'
        return context


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """
    Выводит форму редактирования клиента
    """
    model = Client
    form_class = ClientForm

    success_url = reverse_lazy('mailing:client_list')

    def form_valid(self, form):
        """
        Проверяем данные на правильность заполнения
        """
        self.object = form.save()
        self.object.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(ClientUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Клиенты'
        context['title_2'] = 'Редактирование клиента'
        return context


class ClientDeleteView(DeleteView):
    """
    Выводит форму удаления клиента
    """
    model = Client

    success_url = reverse_lazy('mailing:client_list')

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(ClientDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'Клиенты'
        context['title_2'] = 'Удаление клиента'
        return context


class MessageListView(LoginRequiredMixin, ListView):
    """
    Выводит информаццию о сообщениях пользователя для рассылок
    """
    model = Message
    template_name = 'mailing/message_list.html'

    def get_queryset(self, *args, **kwargs):
        """
        Выводит в список только сообщения конкретного пользователя
        """
        queryset = super().get_queryset(*args, **kwargs)

        queryset = queryset.filter(message_owner=self.request.user)

        return queryset

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(MessageListView, self).get_context_data(**kwargs)

        context['title'] = 'Сообщения'
        context['title_2'] = 'мои сообщения для рассылок'

        return context


class MessageCreateView(LoginRequiredMixin, CreateView):
    """
    Выводит форму создания клиента
    """
    model = Message
    form_class = MessageForm

    success_url = reverse_lazy('mailing:message_list')

    def form_valid(self, form):
        """
        Проверяем данные на правильность заполнения
        """
        self.object = form.save()
        self.object.message_owner = self.request.user
        self.object.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(MessageCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Сообщения'
        context['title_2'] = 'Создание сообщения'
        return context


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """
    Выводит форму редактирования сообщения
    """
    model = Message
    form_class = MessageForm

    success_url = reverse_lazy('mailing:message_list')

    def form_valid(self, form):
        """
        Проверяем данные на правильность заполнения
        """
        self.object = form.save()
        self.object.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(MessageUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Сообщения'
        context['title_2'] = 'Редактирование сообщения'
        return context


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    """
    Выводит форму удаления сообщения
    """
    model = Message

    success_url = reverse_lazy('mailing:message_list')

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(MessageDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'Сообщения'
        context['title_2'] = 'Удаление сообщения'
        return context


def send_mailing_to_clients(request):
    """
    Функция отправки рассылок клиентам
    """

mailing/templates/mailing/includes/inc_mailing_bottom_menu.html
<br>
<footer class="col-lg-10 col-md-6 mx-auto border-top">
    <br>
    <div class="row">
        <div class="col-12 col-md">
            MailingService
            <small class="d-block mb-3 text-muted">&copy; 2023 - {% now 'Y' %}</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>

mailing/templates/mailing/includes/inc_mailing_up_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <nav class="ms-5">
        <div class="col">
            <div class="card bg-warning shadow-sm">
                <div style="background-color:#F0E68C;">
                    <div class="card-body">
                        <a class="p-2 btn btn-secondary" href="{% url 'mailing:home' %}">Главная</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <nav class="ms-5">
        <div class="col">
            <div class="card bg-warning shadow-sm">
                <div style="background-color:#F0E68C;">
                    <div class="card-body">
                        <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:mailing_list' %}">Рассылки</a>

                        <a class="p-2 btn btn-outline-success" href="{% url 'blog:blog_list' %}">Блог</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <nav class="ms-5">
        <div class="col">
            <div class="card bg-warning shadow-sm">
                <div style="background-color:#F0E68C;">
                    <div class="card-body">

                        {% if request.user.is_authenticated %}
                        <div class="badge badge-primary text-wrap text-body" style="width: 10rem;">
                            Привет, {{ request.user.email }}
                        </div>
                        <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
                        <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>
                        {% else %}
                        <div class="badge badge-primary text-wrap text-body" style="width: 10rem;">
                            Войдите в свой аккаунт или зарегистрируйтесь
                        </div>
                        <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
                        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </nav>
{% if request.user.is_staff %}
    <nav class="ms-5">
        <div class="col">
            <div class="card bg-warning shadow-sm">
                <div style="background-color:#F0E68C;">
                    <div class="card-body">
                        <a class="p-2 btn btn-outline-primary" href="{% url 'users:user_list' %}">Пользователи</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>
{% endif %}
</div>